// <auto-generated />
using System;
using GameOfLife.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameOfLife.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("GameOfLife.Models.Human", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("BrainCapacity")
                        .HasColumnType("REAL");

                    b.Property<double>("Engineering")
                        .HasColumnType("REAL");

                    b.Property<double>("Fitness")
                        .HasColumnType("REAL");

                    b.Property<double>("Fun")
                        .HasColumnType("REAL");

                    b.Property<double>("Health")
                        .HasColumnType("REAL");

                    b.Property<double>("Hunger")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Humans");
                });
#pragma warning restore 612, 618
        }
    }
}
